<?php

namespace Burwieck\IphotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{

	// find last posts
	public function getLastAlbums($limit = null)
	{
		return $this->getEntityManager()
	            	->createQuery('SELECT a FROM BurwieckIphotoBundle:Album a ORDER BY a.updated_at DESC')
	            	->setMaxResults($limit)
	            	->getResult();
	}

}