<?php

namespace Burwieck\IphotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaceRepository extends EntityRepository
{

	// find last faces
	public function getLastFaces($limit = 4)
	{
		return $this->getEntityManager()
	            	->createQuery('SELECT f FROM BurwieckIphotoBundle:Face f ORDER BY f.updated_at DESC')
	            	->setMaxResults($limit)
	            	->getResult();
	}

}