<?php

namespace Burwieck\IphotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordRepository extends EntityRepository
{

	// find last keywords
	public function getKeywords($limit = null)
	{
		return $this->getEntityManager()
	            	->createQuery('SELECT k FROM BurwieckIphotoBundle:Keyword k ORDER BY k.updated_at DESC')
	            	->setMaxResults($limit)
	            	->getResult();
	}

}